services:
  tailscale:
    image: tailscale/tailscale
    restart: always
    ports: ["${TS_PORT:-4164}:4164"]
    volumes:
      - ./tailscale:/var/lib/tailscale:rw
      - ${PWD}/config:/config
    environment:
      - TS_SERVE_CONFIG=./config/serve.json
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_HOSTNAME=${TS_HOSTNAME}
      - TS_STATE_DIR=/var/lib/tailscale
    networks:
      - blogscale
    cap_add:
      - net_admin
      - sys_module

  svelte:
    build: .
    network_mode: service:tailscale
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - tailscale

networks:
  blogscale:
    name: blogscale-network
    driver: bridge

volumes:
  tailscale: {}